server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8880/eureka/
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: http://whb@localhost:18080/r/config-repo.git     #or some else uri
         # search-paths: config-repo
