server:
  port: 8885
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8880/eureka/
spring:
  application:
    name: zuul
zuul:
  routes:
    service1:
      path: /service1/**
      serviceId: SERVICE1
    api-a:
      path: /api/**
      serviceId: SERVICE2