server:
  port: 8880
spring:
  application:
    name: eureka
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
  server:
    enable-self-preservation: true
  instance:
    hostname: localhost
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}