server:
  port: 8884
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8880/eureka/
spring:
  application:
    name: service3
#hello-service:
#  ribbon:
#    eureka:
#      enable: true
#    listOfServers: localhost:8882