server:
  port: 8884
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8880/eureka/
spring:
  application:
    name: service3
  cloud:
    loadbalancer:
      retry:
        enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillseconds: 4000
SERVICE1:
  ribbon:
    eureka:
      enable: true
    ConnectTimeout: 4000
    ReadTimeout: 4000
    OkToRetryOnAllOperations: true
    MaxAutoRetriesNextServer: 1
    MaxAutoRetries: 2
    ServerListRefreshInterval: 30000


