server:
  port: 8883
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8880/eureka/
spring:
  application:
    name: service2
services:
  service1:
    name: service1
    baseUrl:
SERVICE1:
  ribbon:
    connectTimeout: 500
    ReadTimeout: 2000
    OkToRetryOnAllOperations: true
    MaxAutoRetriesNextServer: 10
    MaxAutoRetries: 2
feign:
  hystrix:
    enabled: true