server:
  port: 8882
eureka:
#  instance:
#    ip-address: 127.0.0.2
#    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8880/eureka/
spring:
  application:
    name: service1
endpoints:
  metrics:
    sensitive: false
management:
  info:
    git:
      mode: full
